apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
data:
  default.conf: |
    server {
      listen 80;
      server_name minio-api-cluster.lbjt;

      location / {
        proxy_pass http://backend_9000;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
      }

      location /healthz {
        access_log off;
        return 200 'OK';
        add_header Content-Type text/plain;
      }
    }

    server {
      listen 80;
      server_name minio-web-cluster.lbjt;

      location / {
        proxy_pass http://backend_9001;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
      }

      location /healthz {
        access_log off;
        return 200 'OK';
        add_header Content-Type text/plain;
      }
    }

    upstream backend_9000 {
      server 192.168.2.249:9000;
      server 192.168.2.250:9000;
      server 192.168.2.251:9000;
      server 192.168.2.252:9000;
    }

    upstream backend_9001 {
      server 192.168.2.249:9001;
      server 192.168.2.250:9001;
      server 192.168.2.251:9001;
      server 192.168.2.252:9001;
    }
